# Generated by Django 4.0.1 on 2022-01-31 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='img',
            field=models.ImageField(default='something', upload_to='images'),
            preserve_default=False,
        ),
    ]
